// <auto-generated />
using System;
using Demo.Models.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Migrations
{
    [DbContext(typeof(DemoDBContext))]
    [Migration("20230906173228_Test")]
    partial class Test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Demo.Models.CashRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CashRequests");
                });

            modelBuilder.Entity("Demo.Models.Leave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("Demo.Models.CashRequest", b =>
                {
                    b.OwnsMany("CashRequestStatus", "Statuses", b1 =>
                        {
                            b1.Property<Guid>("CashRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.HasKey("CashRequestId", "Id");

                            b1.ToTable("CashRequestStatus");

                            b1.WithOwner()
                                .HasForeignKey("CashRequestId");
                        });

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("Demo.Models.Leave", b =>
                {
                    b.OwnsMany("LeaveStatus", "Statuses", b1 =>
                        {
                            b1.Property<Guid>("LeaveId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.HasKey("LeaveId", "Id");

                            b1.ToTable("LeaveStatus");

                            b1.WithOwner()
                                .HasForeignKey("LeaveId");
                        });

                    b.Navigation("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
